name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to master branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: npm run regen
        env:
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          MEDIUM_USERNAME: ${{ secrets.MEDIUM_USERNAME }}
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          GHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
